spring:
  datasource:
    url: jdbc:mysql://localhost:3306/almundodb?createDatabaseIfNotExist=true&amp;amp;useUnicode=true&amp;amp;characterEncoding=utf-8&amp;amp;autoReconnect=true
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
       dialect: org.hibernate.dialect.MySQL5Dialect
       
           
    